### ISSUE TITLE
Loop and Speed.

### ISSUE THREAD

**Issue by PaolaMonts** [guinhx/ActionRecorder#3]
Hello,

first, excelent project,  

Point #1:
I'm trying to run it with loop[args] and havent find the way.

I try the next:

1. I put under the command /loop[5] and then press the button record, but when i finish the record of the first i press stop.
2. Run the record and press stop and then export the action file and import it again and put under the command /loop[5]
3. using only the loop[5] as for clear you don't use / and its works well.

Point # 2

Its there a way to speed the playback? I'm trying to speed up the process of the recording,

thanks!!!!
Can you let me know how its the step by step way to use the loop?

**Comment by sqmatheus** [comment]
**Hello, thanks for enjoying our project!**

I will assume you used the released version (1.0.0)

**Point # 1:**
 - You don't need to use ``/`` in the console, as everything you send will be implicitly placed with a ``/``.
 - The right way to use the loop is just using: ``loop``.
 - Before recording an action, you need to use  ``loop``, in case the message is: ``When you record an next action list, the same can be reproduced in loop`` the loop is activated.
 - So when you play the record it will be in a loop.
 - We thought about it and the next version will be different using the loop, in this version it's very confusing.
 
**Point # 2:** There's no way to speed up playback, but it's a good idea to put in a new version.
