### ISSUE TITLE
Null reverence

### ISSUE THREAD

**Issue by amboris** [guinhx/ActionRecorder#4]
Hi,

I was trying out the project and encornerd some issue while running in debug mode.

how to replicate:
-run program in debugmode of visual studio
-press f9 to start record
-do some recording
-press f9 to stop record
press f10 to playback

it seems towards the end of the playback
on application.cs:line 166:              sim.PlayBack(_actionFile.Actions);
gets somehow some nullpointer that Playback tries to dereference.

I havent understand the strukture of this project yet, might you be able to fix it?

**Comment by wilianwrech** [comment]
Hello @amboris,
I recently updated this app, you can find a release in my fork, or you can compile it yourself. I am using it for days now and it is working just fine, could you try it again? If the same error happens, I will need more information.
Just a reminder: This new version does not work with old records.

**Comment by amboris** [comment]
quite some changes, works great thanks :)
