### ISSUE TITLE
Any way to compile it into a .exe?

### ISSUE THREAD

**Issue by remi1771** [guinhx/ActionRecorder#6]
Or should I say, is there any chance it'll be compiled as an .exe for easier distribution?

**Comment by alec1o** [comment]
> Requirements
* Visual Studio 2019 or high
  * ``Package`` .NET desktop development
* Source Code

> Steps
* Open ``Visual Studio``
* Select ``Open a project or solution``
* Navigate to ``Source Code`` folder and Select ``ActionRecorder.sln`` file and ``Enter``
* Click on build from visual studio ``tool bar``

``or``

[Download Compiled (``Original Release``)](https://github.com/guinhx/ActionRecorder/releases/tag/v1.0.0)

**Comment by remi1771** [comment]
Thanks!
